name: Java CI with Maven

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Oracle GraalVM
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'graalvm'
        java-package: 'jdk'
        cache: 'maven'
        check-latest: true

    - name: Build and test (with Moditect)
      run: mvn -B -Pmoditect -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2 clean install

    - name: Run E2E tests
      run: mvn -B -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2 -pl zh-learn-e2e test

    - name: Run with modular JVM
      run: ./zh-learn.sh providers

    - name: Build native image
      run: ./build-native.sh

    - name: Run native executable
      run: ./zh-learn-cli/target/zh-learn providers
